config/routes.rb
MassanuttenlionsCom::Application.routes.draw do

  devise_for :users

  mount Ckeditor::Engine => '/ckeditor'

  namespace :mercury do
    resources :images
  end

  mount Mercury::Engine => '/'
  resources :pages, :except => [ :index, :new, :create, :show, :edit, :update, :list,  :destroy, :delete] do
    member { post :mercury_update }
  end
  resources :subjects, :except => :destroy
  match 'admin', :to => 'access#menu'
  match 'show/:id', :to => 'public#show'
  match '/auth/:provider/callback', :to => 'sessions#create'

  root :to => 'static_pages#home'
  authenticated :user do
    root :to => 'static_pages#home'
  end

  match ':controller(/:action(/:id))(.:format)'

end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  layout 'admin'
  before_filter :authenticate_user!
  before_filter :admin_user

  def index
    menu
    render('menu')
  end

  def menu
  end

  def login
  end


end

app/views/access/login.html.erb
<% @page_title= "Admin Login" %>
<hr class="space"/>

<div class="span-12 info push-6">
  <%= form_tag(:action => 'attempt_login') do %>
      <div class="container"><%= label_tag 'Логин' %><%= text_field_tag(:email) %></div>
      <div class="container"><%= label_tag 'Пароль' %><%= password_field_tag(:password) %></div>
      <div class="button-container"><%= submit_tag("Вход") %></div>

      </div>


  <% end %>

app/views/access/menu.html.erb
<% provide(:page_title, 'Admin Home Page') %>
<div class="page-header">
  <h3>Admin Area</h3>
</div>
<div class="well">
  <div class="row-fluid">
    <div class="span12">
      <ul class="thumbnails ">
        <li class="span3">
          <%= link_to(subjects_path, :class => 'thumbnail') do %>
              <h3> Site Information</h3>

              <p>
                <small>Add and edit Subjects, Pages and Sections.</small>
              </p>
          <% end %>
        </li>
        <li class="span3">
          <a href="/newsletters/list" class="thumbnail home-link">
            <h3>Newsletters</h3>

            <p>
              <small> Add and edit Newsletters.</small>
            </p>
          </a>
        </li>
        <li class="span3">
          <a href="/admin/list" class="thumbnail home-link ">
            <h3>Manage Users</h3>

            <p>
              <small>Add and edit members of the club.</small>
            </p>
          </a>
        </li>
        <li class="span3">
          <a href="/club/list" class="thumbnail home-link ">
            <h3>Club Information</h3>

            <p>
              <small> Edit Club Information.</small>
            </p>
          </a>
        </li>
      </ul>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span12">
      <ul class="thumbnails ">
        <li class="span3">
          <a href="https://www.google.com/calendar/render?tab=cc" class="thumbnail home-link " target="_blank">
            <h3>Google Calendar Events</h3>

            <p>
              <small>Add and edit Google Calendar Events.</small>
            </p>
          </a>
        </li>
        <li class="span3">
          <a href="https://www.google.com/analytics/web/?pli=1#report/visitors-overview/a37969295w66499438p68388034/" target="_blank" class="thumbnail home-link">
            <h3>Google Analytics</h3>

            <p>
              <small> Statistics about the visitors to a website.</small>
            </p>
          </a>
        </li>
        <li class="span6">
          <a href=" https://code.google.com/apis/console" target="_blank" class="thumbnail home-link">
            <h3>Google APIs Console</h3>

            <p>
              <small> Web interface for managing and viewing traffic data, authentication, and billing information for the Google APIs.</small>
            </p>
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>